name: Full MLOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      REPO_ID: AkhilRaja/visitwithus-wellness-customer-dataset

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # allows pushing back to GitHub

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub scikit-learn xgboost pandas numpy joblib

      # Step 4: Data preprocessing
      - name: Run data preprocessing
        run: python scripts/preprocess_data.py

      # Step 5: Train & evaluate model
      - name: Train and evaluate model
        run: python scripts/train_model.py

      # Step 6: Push model artifacts to Hugging Face
      - name: Push model artifacts
        run: python scripts/push_to_hf.py

      # Step 7: Commit & push changes to GitHub
      - name: Commit & Push Updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update: data, scripts, or models" || echo "Nothing to commit"
          git push origin main
